version: '3.8'
services:
  app:
    image: php:8.1-fpm
    container_name: wave-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT:-8008}
    command: php artisan serve --host=0.0.0.0 --port=${APP_PORT}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"

  db:
    image: mysql:8
    container_name: wave-db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-wave}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wave}
      - MYSQL_USER=${MYSQL_USER:-wave}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wave}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
