version: '3.8'

networks:
  wave-network:
    driver: bridge

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: builder
    volumes:
      - "../code:/var/www/html"
    working_dir: /var/www/html
    command: tail -f /dev/null
    networks:
      - wave-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: app
    volumes:
      - "../code:/var/www/html"
    working_dir: /var/www/html
    env_file:
      - .env.docker
    depends_on:
      - db
    expose:
      - "${FPM_PORT:-9000}"
    networks:
      - wave-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "${APP_PORT}:80"
    # Basic config: pass PHP requests to 'app' service on port 9000
    # For advanced usage, copy or mount a custom nginx.conf
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/ssl:/etc/nginx/ssl:ro"
      - "../code:/var/www/html"
    command: "nginx -g 'daemon off;'"
    networks:
      - wave-network

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wave-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - wave-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    networks:
      - wave-network

volumes:
  db_data:
